[random]
seed = 137

[temperature]
start = 1000
end = 5
decay_method = "linear" # ["linear", "log"] 
decay = -5

[playground]
x_size = 100
y_size = 100
z_size = 100
init_mode = "random" # ["random", "zero"]
dead_cell_quantity = 0
dead_cell_periodic_unit = [10, 10, 10]

[evolution]
steps_each_temperature = 1500000
steps_observe_interval = 15
steps_preheat = 1500

[energy]
Js = [-0.01928778, ]
Ds = [0.02633423, ]
E_ext = [0.0, 1.0, 1.0, 1.0]
available_states = [
    [1, 1, 1], [-1, 1, 1], [1,-1, 1], [1, 1, -1],
    [-1,-1,1], [-1, 1,-1], [1,-1,-1], [-1,-1,-1]
]
dead_state = [0, 0, 0]

