[random]
seed = 1370

[temperature]
start = 720
end = 20
decay_method = "linear" # ["linear", "log"] 
decay = -15

[playground]
x_size = 20
y_size = 20
z_size = 20
init_mode = "random" # ["random", "zero"]
dead_cell_quantity = 1
dead_cell_periodic_unit = [20, 20, 20]

[evolution]
steps_each_temperature = 80000
steps_observe_interval = 16
steps_preheat = 500

[energy]
Js = [-0.01928778, ]
Ds = [0.0, ]
E_ext = [0.0, 1.0, 1.0, 1.0]
available_states = [
    [1, 1, 1], [-1, 1, 1], [1,-1, 1], [1, 1, -1],
    [-1,-1,1], [-1, 1,-1], [1,-1,-1], [-1,-1,-1]
]
daed_state = [0, 0, 0]

