[random]
seed = 137

[temperature]
start = 1000 # TODO Fix this bug...
end = 5
decay_method = "linear" # ["linear", "log"] 
decay = -5

[playground]
x_size = 20
y_size = 20
z_size = 20
init_mode = "random" # ["random", "zero"]
dead_cell_quantity = 0
dead_cell_periodic_size = [10, 10, 10]

[evolution]
steps_each_temperature = 100000
steps_observe_interval = 20
steps_preheat = 5000

[energy]
Js = [-0.01928778, ]
Ds = [0.0, ]
E_ext = [0.0, 1.0,1.0,1.0]
available_states = [
    [1, 1, 1], [-1, 1, 1], [1,-1, 1], [1, 1, -1],
    [-1,-1,1], [-1, 1,-1], [1,-1,-1], [-1,-1,-1]
]

