[random]
seed = 137

[temperature]
start = 10000
end = 1
decay_method = "log" # ["linear", "log"] 
decay = 0.8

[playground]
x_size = 40
y_size = 40
z_size = 40
init_mode = "random" # ["random", "zero"]
dead_cell_quantity = 0
dead_cell_periodic_unit = [10, 10, 10]

[evolution]
steps_each_temperature = 1300000
steps_observe_interval = 13
steps_preheat = 2000

[energy]
Js = [-0.01928778, ]
Ds = [0.0, ]
E_ext = [0.0, 1.0, 1.0, 1.0]
available_states = [
    [1, 1, 1], [-1, 1, 1], [1,-1, 1], [1, 1, -1],
    [-1,-1,1], [-1, 1,-1], [1,-1,-1], [-1,-1,-1]
]
dead_state = [0, 0, 0]

